apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: kube-system
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      serviceAccountName: falco
      hostPID: true
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-boot
              mountPath: /host/boot
              readOnly: true
            - name: host-lib-modules
              mountPath: /host/lib/modules
              readOnly: true
            - name: host-usr
              mountPath: /host/usr
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-boot
          hostPath:
            path: /boot
            type: DirectoryOrCreate
        - name: host-lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: host-usr
          hostPath:
            path: /usr
            type: Directory
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
