plugin: amazon.aws.aws_ec2

regions:
  - eu-north-1

keyed_groups:
  - key: tags.Role
    prefix: role
  - key: tags.Environment
    prefix: env

filters:
  instance-state-name: running
  tag:Project: "timmy"

hostnames:
  - private-ip-address
  - public-ip-address

compose:
  ansible_host: public_ip_address

strict: False