services:

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 10

  model-init:
    image: ollama/ollama
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: >
      /bin/sh -c "
      ollama pull phi3
      "

  api:
    build: .
    ports:
      - "8022:8000"
    environment:
      PROVIDER: ollama
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: phi3
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data: