- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present
  become: true

- name: Ensure firewalld started and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  become: true

- name: Allow services
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_allow_services }}"
  become: true

- name: Allow custom ports (if any)
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_allow_ports }}"
  become: true