Vagrant.configure("2") do |config|

  BASE_BOX = "bento/ubuntu-24.04"

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = BASE_BOX
    vm1.vm.hostname = "webserver-dynamic"

    vm1.vm.network "public_network", type: "dhcp"

    vm1.vm.synced_folder "./shared_vm1", "/home/vagrant/shared"

    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt update && sudo apt install -y curl
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = BASE_BOX
    vm2.vm.hostname = "private-server"

    vm2.vm.network "private_network", ip: "192.168.56.10"

    vm2.vm.synced_folder "./shared_vm2", "/home/vagrant/shared"

    vm2.vm.provision "shell", path: "provision_vm2.sh"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.box = BASE_BOX
    vm3.vm.hostname = "webserver-static"

    vm3.vm.network "public_network",
      ip: "192.168.1.100",
      bridge: "wlan0"

    vm3.vm.synced_folder "./shared_vm3", "/home/vagrant/shared"
  end
end
